const AFFIRMATIONS = [
  "Small steps today become strong habits tomorrow.",
  "Your encouragement is the best reward your child can receive.",
  "Consistency matters more than perfection—keep showing up.",
  "Every task completed is proof that effort pays off.",
  "You are building trust, focus, and confidence at home.",
  "Celebrate progress, not just outcomes.",
  "A calm routine helps learning feel safe and fun.",
  "Your child learns best when they feel supported, not rushed.",
  "One mindful check-in can change the whole day.",
  "You are guiding growth with patience and care.",
  "Learning happens in many small moments—notice them.",
  "Your presence makes screen time healthier and intentional.",
  "Praise effort and your child will keep trying.",
  "Balance rest, play, and learning—that is real success.",
  "You are teaching responsibility one task at a time.",
  "Trust the process; growth is rarely linear.",
  "Kind boundaries create freedom to focus.",
  "You are doing important work as a learning partner.",
  "Curiosity grows when children feel heard.",
  "Today's patience is tomorrow's confidence.",
  "You model focus every time you follow through together.",
  "Progress is personal—compare only to yesterday.",
  "A short win today can unlock momentum this week.",
  "Your steady support turns challenges into practice.",
  "Healthy habits start with one clear expectation.",
  "You are helping your child build self-discipline.",
  "Celebrate curiosity—it fuels lifelong learning.",
  "Your guidance turns screen time into learning time.",
  "Rest is part of learning; balance protects growth.",
  "You are creating a home where effort is valued.",
  "Every review you give teaches accountability.",
  "Your child can do hard things with your belief in them.",
  "Keep it simple: one priority at a time.",
  "You are planting seeds that will bloom over time.",
  "Gentle reminders are stronger than harsh corrections.",
  "Learning together builds connection and trust.",
  "You are enough—and your effort already matters.",
];

export function getDailyAffirmation(now = new Date()): string {
  const dayIndex = Math.floor(now.getTime() / 86_400_000) % AFFIRMATIONS.length;
  return AFFIRMATIONS[dayIndex] ?? AFFIRMATIONS[0];
}
